name: Rust

on:
  push:
    branches: [ "master", "devel" ]
  pull_request:
    branches: [ "master", "devel" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: taiki-e/install-action@v2.75.28
        with:
          tool: just
      - name: Check formatting
        run: just check-fmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: taiki-e/install-action@v2.75.28
        with:
          tool: just
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Clippy
        run: just clippy

  doc:
    name: Rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: taiki-e/install-action@v2.75.28
        with:
          tool: just
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Check rustdocs
        run: just check-doc

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: taiki-e/install-action@v2.75.28
        with:
          tool: just
      - uses: Swatinem/rust-cache@v2.9.1
      - name: Run tests
        run: just test-full
